/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {

    public static void main(String... args){

        final MessageCreator messageCreator = new MessageCreator();

        System.out.println(messageCreator.createMessage());
    }
}
